/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Vini
 */
public class EditarTorneio extends javax.swing.JFrame {

    /**
     * Creates new form EditarTorneio
     */
    public EditarTorneio() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblPartidaAtual = new javax.swing.JLabel();
        lblNomeJogadores = new javax.swing.JLabel();
        txtPontosJogador1 = new javax.swing.JTextField();
        txtPontosJogador2 = new javax.swing.JTextField();
        lblNumeroJogo = new javax.swing.JLabel();
        lblx = new javax.swing.JLabel();
        lblNumeroJogoNum = new javax.swing.JLabel();
        btnAdicionarResultado = new javax.swing.JButton();
        ckxCapote = new javax.swing.JCheckBox();
        btnEncerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Editar Torneio");

        lblPartidaAtual.setText("Partida Atual:");

        lblNomeJogadores.setText("Fulaninho    X   Beltraninho");

        txtPontosJogador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPontosJogador2ActionPerformed(evt);
            }
        });

        lblNumeroJogo.setText("Numero do Jogo:");

        lblx.setText("X");

        lblNumeroJogoNum.setText("1");

        btnAdicionarResultado.setText("Adicionar Resultado");

        ckxCapote.setText("Capote");

        btnEncerrar.setText("Encerrar Torneio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPartidaAtual)
                                .addGap(118, 118, 118)
                                .addComponent(lblNomeJogadores))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNumeroJogo)
                                .addGap(12, 12, 12)
                                .addComponent(lblNumeroJogoNum)
                                .addGap(52, 52, 52)
                                .addComponent(txtPontosJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblx)
                                .addGap(18, 18, 18)
                                .addComponent(txtPontosJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(btnAdicionarResultado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(ckxCapote))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(btnEncerrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(lblTitulo)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPartidaAtual)
                    .addComponent(lblNomeJogadores))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPontosJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPontosJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroJogo)
                    .addComponent(lblx)
                    .addComponent(lblNumeroJogoNum))
                .addGap(18, 18, 18)
                .addComponent(ckxCapote)
                .addGap(36, 36, 36)
                .addComponent(btnAdicionarResultado)
                .addGap(121, 121, 121)
                .addComponent(btnEncerrar)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPontosJogador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPontosJogador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPontosJogador2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarTorneio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarTorneio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarTorneio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarTorneio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarTorneio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarResultado;
    private javax.swing.JButton btnEncerrar;
    private javax.swing.JCheckBox ckxCapote;
    private javax.swing.JLabel lblNomeJogadores;
    private javax.swing.JLabel lblNumeroJogo;
    private javax.swing.JLabel lblNumeroJogoNum;
    private javax.swing.JLabel lblPartidaAtual;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblx;
    private javax.swing.JTextField txtPontosJogador1;
    private javax.swing.JTextField txtPontosJogador2;
    // End of variables declaration//GEN-END:variables
}
