/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.util.ArrayList;
import trabalhofinal.TrabalhoFinal;
import trabalhofinal.Partida;
/**
 *
 * @author guton
 */
public class MataMataPontuacao extends javax.swing.JFrame {

    /**
     * Creates new form MataMataPOntuacao
     */
    public MataMataPontuacao() {
        initComponents();
        setLocationRelativeTo(null);
        this.setup();
    }

    public void setup(){
        ArrayList<javax.swing.JLabel> labels1 = new ArrayList();
        labels1.add(lblJogo1);
        labels1.add(lblJogo1);
        labels1.add(lblJogo2);
        labels1.add(lblJogo3);
        labels1.add(lblJogo4);
        labels1.add(lblJogo5);
        labels1.add(lblJogo6);
        labels1.add(lblJogo7);
        labels1.add(lblJogo8);
        labels1.add(lblJogo9);
        labels1.add(lblJogo10);
        labels1.add(lblJogo11);
        labels1.add(lblJogo12);
        labels1.add(lblJogo13);
        labels1.add(lblJogo14);
        labels1.add(lblJogo15);
        
        ArrayList<javax.swing.JLabel> labels2 = new ArrayList();
        labels1.add(lblResultado1);
        labels1.add(lblResultado2);
        labels1.add(lblResultado3);
        labels1.add(lblResultado4);
        labels1.add(lblResultado5);
        labels1.add(lblResultado6);
        labels1.add(lblResultado7);
        labels1.add(lblResultado8);
        labels1.add(lblResultado9);
        labels1.add(lblResultado10);
        labels1.add(lblResultado11);
        labels1.add(lblResultado12);
        labels1.add(lblResultado13);
        labels1.add(lblResultado14);
        labels1.add(lblResultado15);
        
        ArrayList<Partida> partidas = TrabalhoFinal.currentTorneio.getPartidas();
        
        if(TrabalhoFinal.currentTorneio.getEstado() == 2){
            for(int i = 0; i < partidas.size(); i++){
                labels1.get(i).setText(String.format("%s x %s", partidas.get(i).getP1().getNome(), partidas.get(i).getP2().getNome()));
                ArrayList<Integer> resultado = partidas.get(i).getResultado();
                labels2.get(i).setText(String.format("%d x %d", resultado.get(0), resultado.get(0)));
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panOitavas = new javax.swing.JPanel();
        panJogo1 = new javax.swing.JPanel();
        lblJogo1 = new javax.swing.JLabel();
        lblResultado1 = new javax.swing.JLabel();
        panJogo3 = new javax.swing.JPanel();
        lblJogo3 = new javax.swing.JLabel();
        lblResultado3 = new javax.swing.JLabel();
        panJogo5 = new javax.swing.JPanel();
        lblJogo5 = new javax.swing.JLabel();
        lblResultado5 = new javax.swing.JLabel();
        panJogo2 = new javax.swing.JPanel();
        lblJogo2 = new javax.swing.JLabel();
        lblResultado2 = new javax.swing.JLabel();
        panJogo4 = new javax.swing.JPanel();
        lblJogo4 = new javax.swing.JLabel();
        lblResultado4 = new javax.swing.JLabel();
        panJogo6 = new javax.swing.JPanel();
        lblJogo6 = new javax.swing.JLabel();
        lblResultado6 = new javax.swing.JLabel();
        panJogo7 = new javax.swing.JPanel();
        lblJogo7 = new javax.swing.JLabel();
        lblResultado7 = new javax.swing.JLabel();
        panJogo8 = new javax.swing.JPanel();
        lblJogo8 = new javax.swing.JLabel();
        lblResultado8 = new javax.swing.JLabel();
        panQuartas = new javax.swing.JPanel();
        panJogo9 = new javax.swing.JPanel();
        lblJogo9 = new javax.swing.JLabel();
        lblResultado9 = new javax.swing.JLabel();
        panJogo10 = new javax.swing.JPanel();
        lblJogo10 = new javax.swing.JLabel();
        lblResultado10 = new javax.swing.JLabel();
        panJogo12 = new javax.swing.JPanel();
        lblJogo12 = new javax.swing.JLabel();
        lblResultado12 = new javax.swing.JLabel();
        panJogo11 = new javax.swing.JPanel();
        lblJogo11 = new javax.swing.JLabel();
        lblResultado11 = new javax.swing.JLabel();
        panSemi = new javax.swing.JPanel();
        panJogo13 = new javax.swing.JPanel();
        lblJogo13 = new javax.swing.JLabel();
        lblResultado13 = new javax.swing.JLabel();
        panJogo14 = new javax.swing.JPanel();
        lblJogo14 = new javax.swing.JLabel();
        lblResultado14 = new javax.swing.JLabel();
        panFinal = new javax.swing.JPanel();
        panJogo15 = new javax.swing.JPanel();
        lblJogo15 = new javax.swing.JLabel();
        lblResultado15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panJogo1.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogo 1"));

        lblJogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJogo1.setText("-");

        lblResultado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado1.setText("0 x 0");

        javax.swing.GroupLayout panJogo1Layout = new javax.swing.GroupLayout(panJogo1);
        panJogo1.setLayout(panJogo1Layout);
        panJogo1Layout.setHorizontalGroup(
            panJogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogo1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panJogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panJogo1Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(lblResultado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblJogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        panJogo1Layout.setVerticalGroup(
            panJogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJogo1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblJogo1)
                .addGap(10, 10, 10)
                .addComponent(lblResultado1)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panJogo3.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogo 3"));

        lblJogo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJogo3.setText("-");

        lblResultado3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado3.setText("0 x 0");

        javax.swing.GroupLayout panJogo3Layout = new javax.swing.GroupLayout(panJogo3);
        panJogo3.setLayout(panJogo3Layout);
        panJogo3Layout.setHorizontalGroup(
            panJogo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogo3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panJogo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblResultado3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJogo3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        panJogo3Layout.setVerticalGroup(
            panJogo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJogo3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblJogo3)
                .addGap(10, 10, 10)
                .addComponent(lblResultado3)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panJogo5.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogo 5"));

        lblJogo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJogo5.setText("-");

        lblResultado5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado5.setText("0 x 0");

        javax.swing.GroupLayout panJogo5Layout = new javax.swing.GroupLayout(panJogo5);
        panJogo5.setLayout(panJogo5Layout);
        panJogo5Layout.setHorizontalGroup(
            panJogo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogo5Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panJogo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblResultado5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJogo5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        panJogo5Layout.setVerticalGroup(
            panJogo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJogo5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblJogo5)
                .addGap(10, 10, 10)
                .addComponent(lblResultado5)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panJogo2.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogo 2"));

        lblJogo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJogo2.setText("-");

        lblResultado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado2.setText("0 x 0");

        javax.swing.GroupLayout panJogo2Layout = new javax.swing.GroupLayout(panJogo2);
        panJogo2.setLayout(panJogo2Layout);
        panJogo2Layout.setHorizontalGroup(
            panJogo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogo2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panJogo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblResultado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJogo2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        panJogo2Layout.setVerticalGroup(
            panJogo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJogo2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblJogo2)
                .addGap(10, 10, 10)
                .addComponent(lblResultado2)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panJogo4.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogo 4"));

        lblJogo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJogo4.setText("-");

        lblResultado4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado4.setText("0 x 0");

        javax.swing.GroupLayout panJogo4Layout = new javax.swing.GroupLayout(panJogo4);
        panJogo4.setLayout(panJogo4Layout);
        panJogo4Layout.setHorizontalGroup(
            panJogo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogo4Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panJogo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblResultado4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJogo4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        panJogo4Layout.setVerticalGroup(
            panJogo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJogo4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblJogo4)
                .addGap(10, 10, 10)
                .addComponent(lblResultado4)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panJogo6.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogo 6"));

        lblJogo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJogo6.setText("-");

        lblResultado6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado6.setText("0 x 0");

        javax.swing.GroupLayout panJogo6Layout = new javax.swing.GroupLayout(panJogo6);
        panJogo6.setLayout(panJogo6Layout);
        panJogo6Layout.setHorizontalGroup(
            panJogo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogo6Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panJogo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblResultado6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJogo6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        panJogo6Layout.setVerticalGroup(
            panJogo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJogo6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblJogo6)
                .addGap(10, 10, 10)
                .addComponent(lblResultado6)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panJogo7.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogo 7"));

        lblJogo7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJogo7.setText("-");

        lblResultado7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado7.setText("0 x 0");

        javax.swing.GroupLayout panJogo7Layout = new javax.swing.GroupLayout(panJogo7);
        panJogo7.setLayout(panJogo7Layout);
        panJogo7Layout.setHorizontalGroup(
            panJogo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogo7Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panJogo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblResultado7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJogo7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        panJogo7Layout.setVerticalGroup(
            panJogo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJogo7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblJogo7)
                .addGap(10, 10, 10)
                .addComponent(lblResultado7)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panJogo8.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogo 8"));

        lblJogo8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJogo8.setText("-");

        lblResultado8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado8.setText("0 x 0");

        javax.swing.GroupLayout panJogo8Layout = new javax.swing.GroupLayout(panJogo8);
        panJogo8.setLayout(panJogo8Layout);
        panJogo8Layout.setHorizontalGroup(
            panJogo8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogo8Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panJogo8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblResultado8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJogo8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        panJogo8Layout.setVerticalGroup(
            panJogo8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJogo8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblJogo8)
                .addGap(10, 10, 10)
                .addComponent(lblResultado8)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panOitavasLayout = new javax.swing.GroupLayout(panOitavas);
        panOitavas.setLayout(panOitavasLayout);
        panOitavasLayout.setHorizontalGroup(
            panOitavasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOitavasLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(panOitavasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panJogo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panJogo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panJogo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panJogo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(panOitavasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panJogo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panJogo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panJogo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panJogo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        panOitavasLayout.setVerticalGroup(
            panOitavasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOitavasLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panOitavasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panJogo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panJogo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panOitavasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panJogo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panJogo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panOitavasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panJogo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panJogo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panOitavasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panJogo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panJogo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Oitavas de final", panOitavas);

        panJogo9.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogo 9"));

        lblJogo9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJogo9.setText("-");

        lblResultado9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado9.setText("0 x 0");

        javax.swing.GroupLayout panJogo9Layout = new javax.swing.GroupLayout(panJogo9);
        panJogo9.setLayout(panJogo9Layout);
        panJogo9Layout.setHorizontalGroup(
            panJogo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogo9Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panJogo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblResultado9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJogo9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        panJogo9Layout.setVerticalGroup(
            panJogo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJogo9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblJogo9)
                .addGap(10, 10, 10)
                .addComponent(lblResultado9)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panJogo10.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogo 10"));

        lblJogo10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJogo10.setText("-");

        lblResultado10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado10.setText("0 x 0");

        javax.swing.GroupLayout panJogo10Layout = new javax.swing.GroupLayout(panJogo10);
        panJogo10.setLayout(panJogo10Layout);
        panJogo10Layout.setHorizontalGroup(
            panJogo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogo10Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panJogo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblResultado10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJogo10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        panJogo10Layout.setVerticalGroup(
            panJogo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJogo10Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblJogo10)
                .addGap(10, 10, 10)
                .addComponent(lblResultado10)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panJogo12.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogo 12"));

        lblJogo12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJogo12.setText("-");

        lblResultado12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado12.setText("0 x 0");

        javax.swing.GroupLayout panJogo12Layout = new javax.swing.GroupLayout(panJogo12);
        panJogo12.setLayout(panJogo12Layout);
        panJogo12Layout.setHorizontalGroup(
            panJogo12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogo12Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panJogo12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblResultado12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJogo12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        panJogo12Layout.setVerticalGroup(
            panJogo12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJogo12Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblJogo12)
                .addGap(10, 10, 10)
                .addComponent(lblResultado12)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panJogo11.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogo 11"));

        lblJogo11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJogo11.setText("-");

        lblResultado11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado11.setText("0 x 0");

        javax.swing.GroupLayout panJogo11Layout = new javax.swing.GroupLayout(panJogo11);
        panJogo11.setLayout(panJogo11Layout);
        panJogo11Layout.setHorizontalGroup(
            panJogo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogo11Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panJogo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblResultado11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJogo11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        panJogo11Layout.setVerticalGroup(
            panJogo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJogo11Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblJogo11)
                .addGap(10, 10, 10)
                .addComponent(lblResultado11)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panQuartasLayout = new javax.swing.GroupLayout(panQuartas);
        panQuartas.setLayout(panQuartasLayout);
        panQuartasLayout.setHorizontalGroup(
            panQuartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
            .addGroup(panQuartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panQuartasLayout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addGroup(panQuartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panJogo9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panJogo11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(42, 42, 42)
                    .addGroup(panQuartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panJogo12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panJogo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(73, Short.MAX_VALUE)))
        );
        panQuartasLayout.setVerticalGroup(
            panQuartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
            .addGroup(panQuartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panQuartasLayout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addGroup(panQuartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panJogo9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panJogo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panQuartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panJogo11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panJogo12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(116, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Quartas de final", panQuartas);

        panJogo13.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogo 13"));

        lblJogo13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJogo13.setText("-");

        lblResultado13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado13.setText("0 x 0");

        javax.swing.GroupLayout panJogo13Layout = new javax.swing.GroupLayout(panJogo13);
        panJogo13.setLayout(panJogo13Layout);
        panJogo13Layout.setHorizontalGroup(
            panJogo13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogo13Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panJogo13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblResultado13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJogo13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        panJogo13Layout.setVerticalGroup(
            panJogo13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJogo13Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblJogo13)
                .addGap(10, 10, 10)
                .addComponent(lblResultado13)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panJogo14.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogo 14"));

        lblJogo14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJogo14.setText("-");

        lblResultado14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado14.setText("0 x 0");

        javax.swing.GroupLayout panJogo14Layout = new javax.swing.GroupLayout(panJogo14);
        panJogo14.setLayout(panJogo14Layout);
        panJogo14Layout.setHorizontalGroup(
            panJogo14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogo14Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panJogo14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblResultado14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJogo14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        panJogo14Layout.setVerticalGroup(
            panJogo14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJogo14Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblJogo14)
                .addGap(10, 10, 10)
                .addComponent(lblResultado14)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panSemiLayout = new javax.swing.GroupLayout(panSemi);
        panSemi.setLayout(panSemiLayout);
        panSemiLayout.setHorizontalGroup(
            panSemiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
            .addGroup(panSemiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panSemiLayout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(panJogo13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(42, 42, 42)
                    .addComponent(panJogo14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(73, Short.MAX_VALUE)))
        );
        panSemiLayout.setVerticalGroup(
            panSemiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
            .addGroup(panSemiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panSemiLayout.createSequentialGroup()
                    .addGap(161, 161, 161)
                    .addGroup(panSemiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panJogo13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panJogo14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(162, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Semifinais", panSemi);

        panJogo15.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogo 15"));

        lblJogo15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJogo15.setText("-");

        lblResultado15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado15.setText("0 x 0");

        javax.swing.GroupLayout panJogo15Layout = new javax.swing.GroupLayout(panJogo15);
        panJogo15.setLayout(panJogo15Layout);
        panJogo15Layout.setHorizontalGroup(
            panJogo15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogo15Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panJogo15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblResultado15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJogo15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        panJogo15Layout.setVerticalGroup(
            panJogo15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJogo15Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblJogo15)
                .addGap(10, 10, 10)
                .addComponent(lblResultado15)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panFinalLayout = new javax.swing.GroupLayout(panFinal);
        panFinal.setLayout(panFinalLayout);
        panFinalLayout.setHorizontalGroup(
            panFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
            .addGroup(panFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panFinalLayout.createSequentialGroup()
                    .addGap(209, 209, 209)
                    .addComponent(panJogo15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(209, Short.MAX_VALUE)))
        );
        panFinalLayout.setVerticalGroup(
            panFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
            .addGroup(panFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panFinalLayout.createSequentialGroup()
                    .addGap(161, 161, 161)
                    .addComponent(panJogo15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(162, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Final", panFinal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MataMataPontuacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MataMataPontuacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MataMataPontuacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MataMataPontuacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MataMataPontuacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblJogo1;
    private javax.swing.JLabel lblJogo10;
    private javax.swing.JLabel lblJogo11;
    private javax.swing.JLabel lblJogo12;
    private javax.swing.JLabel lblJogo13;
    private javax.swing.JLabel lblJogo14;
    private javax.swing.JLabel lblJogo15;
    private javax.swing.JLabel lblJogo2;
    private javax.swing.JLabel lblJogo3;
    private javax.swing.JLabel lblJogo4;
    private javax.swing.JLabel lblJogo5;
    private javax.swing.JLabel lblJogo6;
    private javax.swing.JLabel lblJogo7;
    private javax.swing.JLabel lblJogo8;
    private javax.swing.JLabel lblJogo9;
    private javax.swing.JLabel lblResultado1;
    private javax.swing.JLabel lblResultado10;
    private javax.swing.JLabel lblResultado11;
    private javax.swing.JLabel lblResultado12;
    private javax.swing.JLabel lblResultado13;
    private javax.swing.JLabel lblResultado14;
    private javax.swing.JLabel lblResultado15;
    private javax.swing.JLabel lblResultado2;
    private javax.swing.JLabel lblResultado3;
    private javax.swing.JLabel lblResultado4;
    private javax.swing.JLabel lblResultado5;
    private javax.swing.JLabel lblResultado6;
    private javax.swing.JLabel lblResultado7;
    private javax.swing.JLabel lblResultado8;
    private javax.swing.JLabel lblResultado9;
    private javax.swing.JPanel panFinal;
    private javax.swing.JPanel panJogo1;
    private javax.swing.JPanel panJogo10;
    private javax.swing.JPanel panJogo11;
    private javax.swing.JPanel panJogo12;
    private javax.swing.JPanel panJogo13;
    private javax.swing.JPanel panJogo14;
    private javax.swing.JPanel panJogo15;
    private javax.swing.JPanel panJogo2;
    private javax.swing.JPanel panJogo3;
    private javax.swing.JPanel panJogo4;
    private javax.swing.JPanel panJogo5;
    private javax.swing.JPanel panJogo6;
    private javax.swing.JPanel panJogo7;
    private javax.swing.JPanel panJogo8;
    private javax.swing.JPanel panJogo9;
    private javax.swing.JPanel panOitavas;
    private javax.swing.JPanel panQuartas;
    private javax.swing.JPanel panSemi;
    // End of variables declaration//GEN-END:variables
}
