/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package telas;

/**
 *
 * @author Vini
 */
public class TorneioInfo extends javax.swing.JPanel {

    /**
     * Creates new form TorneioInfo
     */
    public TorneioInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblLocal = new javax.swing.JLabel();
        lblRegra = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblMaxPart = new javax.swing.JLabel();
        lblMinPart = new javax.swing.JLabel();
        lblInicioInscr = new javax.swing.JLabel();
        lblFimInscr = new javax.swing.JLabel();
        lblInicioJogos = new javax.swing.JLabel();
        lblFimJogos = new javax.swing.JLabel();
        lblNumJogos = new javax.swing.JLabel();
        btnListaPart = new javax.swing.JButton();
        btnPontuacao = new javax.swing.JButton();
        btnInscricao = new javax.swing.JButton();
        btnCancelaInscr = new javax.swing.JButton();
        btnEditarTorneio = new javax.swing.JButton();

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Torneio do Tio Zé");

        lblDescricao.setText("Descrição ");

        lblLocal.setText("Local: ");

        lblRegra.setText("Regra:");

        lblTipo.setText("Tipo:");

        lblMaxPart.setText("Máximo de participantes:");

        lblMinPart.setText("Mínimo de participantes:");

        lblInicioInscr.setText("Início das Inscrições:");

        lblFimInscr.setText("Encerramento das Incrições:");

        lblInicioJogos.setText("Inicío dos Jogos:");

        lblFimJogos.setText("Fim dos Jogos:");

        lblNumJogos.setText("Número de jogos por partida:");

        btnListaPart.setText("Lista de participantes");

        btnPontuacao.setText("Pontuação");

        btnInscricao.setText("Inscrever-se");

        btnCancelaInscr.setText("Cancelar Inscrição");

        btnEditarTorneio.setText("Editar Torneio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblTitulo)
                            .addGap(58, 58, 58)
                            .addComponent(btnEditarTorneio)
                            .addGap(57, 57, 57))
                        .addComponent(lblDescricao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLocal)
                            .addComponent(lblRegra)
                            .addComponent(lblTipo)
                            .addComponent(lblMaxPart)
                            .addComponent(lblMinPart)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnListaPart)
                                .addGap(18, 18, 18)
                                .addComponent(btnPontuacao)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFimInscr)
                            .addComponent(lblInicioInscr)
                            .addComponent(lblInicioJogos)
                            .addComponent(lblFimJogos)
                            .addComponent(lblNumJogos)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInscricao)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelaInscr)))
                        .addGap(178, 178, 178))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblTitulo)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEditarTorneio)
                        .addGap(28, 28, 28)))
                .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocal)
                    .addComponent(lblInicioInscr))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegra)
                    .addComponent(lblFimInscr))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(lblInicioJogos))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxPart)
                    .addComponent(lblFimJogos))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinPart)
                    .addComponent(lblNumJogos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListaPart)
                    .addComponent(btnPontuacao)
                    .addComponent(btnInscricao)
                    .addComponent(btnCancelaInscr))
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelaInscr;
    private javax.swing.JButton btnEditarTorneio;
    private javax.swing.JButton btnInscricao;
    private javax.swing.JButton btnListaPart;
    private javax.swing.JButton btnPontuacao;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblFimInscr;
    private javax.swing.JLabel lblFimJogos;
    private javax.swing.JLabel lblInicioInscr;
    private javax.swing.JLabel lblInicioJogos;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JLabel lblMaxPart;
    private javax.swing.JLabel lblMinPart;
    private javax.swing.JLabel lblNumJogos;
    private javax.swing.JLabel lblRegra;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
